### ISSUE TITLE
Can not pull

### ISSUE THREAD

**Issue by chuyengiason** [termius/termius-cli#114]
Hi, 
I ran mac os sierra and installed termius cli via homebrew. 
Installed without problem. Can log in successfully but when I ran : termius pull, the command output error : [Errno 13] Permission denied: '/document'
Can you help to check?

**Comment by EvgeneOskin** [comment]
Hey, 
Thanks for reporting this. We have an issue with saving keys with labels starting with `/`. As a workaround, please remove start`/` from the ssh key label.

**Comment by EvgeneOskin** [comment]
I close this issue as a duplicate with #133.
