### ISSUE TITLE
A switch of upgrade 

### ISSUE THREAD

**Issue by HelperInCa** [termius/termius-cli#172]
Hi,

I am a devloper on MacOS. I need a more undisturbed environment, but the upgrade is too often for me. So I suggest a switch of upgrade, then users can upgrade by theirself.

**Comment by EvgeneOskin** [comment]
Hi @HelperInCa,
Is this issue with the Desktop app? We don't update termius-cli often. 
Please submit your feature request to our product roadmap – https://ideas.termius.com/
