### ISSUE TITLE
bug: export-ssh-config doesn't work

### ISSUE THREAD

**Issue by alexander-potemkin** [termius/termius-cli#173]
Bug report:
```
 % termius export-ssh-config
Export hosts from local storage to ~/.termius/sshconfig

% cat ~/.termius/sshconfig

%
```
The resulting file is empty.

Details:
```
% uname -a
Darwin MyMacBook.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

% termius --version
termius 1.2.15
```

**Comment by EvgeneOskin** [comment]
@alexander-potemkin, thanks for reporting. We discuss this issue with you via email.

For someone who come to this comment in the future, there could be two reasons for missed export:
1. termius-cli doesn't have data locally, or data is not synced with the cloud. A solution is to trigger sync manually in the termius devices in "Account -> Sync Now" and to init termius-cli with a command `termius init`.
2. there is the only team that shared data in termius. At the moment, termius-cli does not pull shared data. Please submit your feature request to our product roadmap – https://ideas.teams.termius.com/.

**Comment by alexander-potemkin** [comment]
@EvgeneOskin , the one in the e-mail is a bit different, though.

This particular issue was fixed by making app sync work. And, what is important, it's to make sure that sync includes all of the keys and credentials, which is not on by default and have issues while enabling it on iOS (need to tap a few times and come back and check if it happened actually).

**Comment by lexxnsk** [comment]
Should I have Premium to be able to export config locally by termius export-ssh-config ?

**Comment by alexander-potemkin** [comment]
You won’t get your ssh keys & passwords even if you pay 10 times premium. I’m on a paid subscription and that doesn’t change a thing.

**Comment by lexxnsk** [comment]
This is sad 🤨

**Comment by lexxnsk** [comment]
@alexander-potemkin but do you have at least your ssh sessions backed up by Termius cli? I am getting empty file

**Comment by alexander-potemkin** [comment]
List of servers - yes, that I get.
I’m sorry to hear it doesn’t work for you - indeed export mechanics doesn’t seem to be developed

**Comment by alexander-potemkin** [comment]
@EvgeneOskin why did you close the ticket, by the way?

**Comment by fenris** [comment]
looking forward to see the termius-cli to be updated and solve this issue ...

**Comment by alexander-potemkin** [comment]
Hope you would be of more luck, @fenris 
I was ignored for a few years, moved to iTerm and ssh' config ever since, absolutely happy, free of charge.
