### ISSUE TITLE
Can not connect to local network in Ipados14

### ISSUE THREAD

**Issue by coding-famer** [termius/termius-cli#185]
can not connect to local network in Ipados14

**Comment by EvgeneOskin** [comment]
Hi @coding-famer,
Could you please double-check that the app has "Local Network" permission – [a troubleshooting article about the issue](https://support.termius.com/hc/en-us/articles/4403533781017-I-get-the-no-route-to-host-error-message)?

**Comment by coding-famer** [comment]
Sorry but I couldn't found Local Network permission in my Termius
settings[image:
3CF6B96A4678997ECFD5662633ABD852.png]

**Comment by EvgeneOskin** [comment]
I see. A closer investigation is required.
Could you please report the issue on support.termius.com? 
Our iOS team will take it from there and will update the article after the investigation.

**Comment by coding-famer** [comment]
Sure, I will do that.
