### ISSUE TITLE
"The current version of Termius CLI is incompatible with new Termius encryption algorithms."

### ISSUE THREAD

**Issue by makanikai** [termius/termius-cli#188]
Mac OS X Monterey - Arm64 (Mac m1)

Tried Brew, Pip, Easy installs

I get "The current version of Termius CLI is incompatible with new Termius encryption algorithms."

I have 2fa on my account.

 When i try 
`termius init --verbose`

I get

```
Initializing Termius CLI...

Please enter your Termius credentials

Username: XXXXXXXX email omitted from issue XXXXX
Password:
Starting new HTTPS connection (1): api.termius.com:443
https://api.termius.com:443 "POST /api/v3.1/login/ HTTP/1.1" 490 38
Can not login!

```

Anything else I should be trying? Thanks!  Love the app, have been a paid user for a while and this cli integration is just what I need to link everything together (with my usual iTerm workflow).

**Comment by ITHoneyBadger** [comment]
@makanikai have you had any luck with this?  I set it up today and am running into the same issue.

**Comment by gabeklavans** [comment]
I'm assuming it has to do with the new encryption algorithms they just rolled out on the main app... I just upgraded my account it use it and am getting this same error. My guess is they just haven't updated the CLI to support it yet.

**Comment by TimDowker** [comment]
Still have this issue myself.  Hope they update it soon.

**Comment by TimDowker** [comment]
Um, is this ever going to be updated?  The new excryption method employed by the desktop client has been out for bit now.

**Comment by lfkdev** [comment]
This problem still exist and basically renders the cli tool worthless / unusable.

**Comment by Vikinge** [comment]
Are there any other options to export hosts from Termius

**Comment by skitzo2000** [comment]
I was super excited to find this feature as I'm a newer user to termius.  Only to find out it's no longer usable.  I have a lot of hosts in termius(200+atm and growing).   Exporting would be way better than scanning through termius to build my config file...

**Comment by normal-coder** [comment]
I am an early user of termius and a heavy user of the CLI. I use termius-cli to sync my configuration between desktop client and iTerm2. But it's a pity to encounter such a problem. Basically the project was scrapped. By comparison. For my personal use this tool. Seems like service subscriptions are of no value to me. Will this project continue to be maintained? Will there be a new CLI client?

**Comment by i5o** [comment]
Hate to add nothing to this thread but the same message.
Anyone knows a solution to export ssh configs/hosts into a new machine?

**Comment by cjangrist** [comment]
also lookinf for algernative app with cli option 🤔

**Comment by huaiyizhao** [comment]
Same problem. The way they let their app *import* from other sources but not *export* is where I find disappointment.

**Comment by chemputer** [comment]
> Same problem. The way they let their app _import_ from other sources but not _export_ is where I find disappointment.

They want you to join, get hooked, then pay for features and if you want to leave, well, good luck, no export functionality. They'll help you get on board but they will not help you get out. That's some really shady business practices right there.

**Comment by Lioness100** [comment]
Very disappointed with the inability to export to ssh config...

**Comment by rithvikvibhu** [comment]
Are there any plans to update this package to make this work?

**Comment by dtap001** [comment]
what now??!!!!

**Comment by astromandev** [comment]
when is it gonan be fixed the issue  has been here for a year 
very disapointed from the termius team

**Comment by bovi** [comment]
Yeah what's that here? Still not fixed since nearly two years.

**Comment by chemputer** [comment]
> Are there any plans to update this package to make this work? 

@rithvikvibhu 

> when is it gonan be fixed the issue has been here for a year very disapointed from the termius team

@astromandev 

Not that anyone from Termius has said, and I wouldn't expect anything from them. They seem to have stopped developing anything customer-facing as open-source software as far as I can tell.

Even if they aren't saying so explicitly (which I seem to remember them saying as much somewhere a while ago but cannot find it anymore), this is, by default, now, deprecated and no longer supported. 

Could they change that? Sure? Is that likely after 2 years? Not even remotely! 

So really, there's no benefit to making a comment without any substance reviving a thread that's been dead for quite some time.  Most of us on GitHub get push notifications when an issue we've commented on are commented on, so all you're really doing, intentionally or not, is bugging fellow (former) users who were or are in the same position as you are now, and are just as frustrated with the company as you are.

If I may, I'd suggest something like [MobaXterm](https://mobaxterm.mobatek.net/) if you're on Windows. It's a quality product that has been well-supported for a very long time, alternatively, any of the more feature-rich PuTTY forks are good too, such as KiTTY.
[mRemoteNG ](https://mremoteng.org/) is also another good one that is cross-platform and also FOSS, loads of features, but as far as I can tell, you do go without the ease-of-use encrypted syncing, which sucks, yes, but it is what it is.

It's a shame, too, as Termius has a good product, but they want too much for it, and they don't provide a way to easily export your data (as in other than manually doing so).

**Comment by rkudiyarov** [comment]
Yes, the lack of communication about this feature is unacceptable. We will try to be more transparent next time.

We had a big initiative in the company to upgrade encryption and move to the concept of the vault from sharing. It was a huge effort, and we had to neglect several parts of the product to deliver it as quickly as possible. It took us a couple of years overall while API and CLI were out of scope. We released the biggest chunk of vaults yesterday, and we started to look into API and CLI. If you are still interested in this feature please hit by email roman [at] termius [dot] com.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/termius/termius-cli/issues/188#event-11241361023

@rkudiyarov, since you closed this issue as https://github.com/termius/termius-cli/issues?q=is%3Aissue+reason%3Acompleted, can you confirm that this issue has been remediated?
