### ISSUE TITLE
New Snap Version of Termius is not Compatible with Fish-shell

### ISSUE THREAD

**Issue by Natgho** [termius/termius-cli#201]
```bash
ubuntu@hidden ~ [127]>  fish --version
fish, version 3.3.1
ubuntu@hidden ~> echo $version
3.3.1
ubuntu@hidden ~> uname -a
Linux hidden 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
I am using Ubuntu mate and Termius app.
When I connect SSH to my server (it started from directly fish, I did it with "chsh -s /bin/fish" and it worked) fish is showing this error;
![image](https://user-images.githubusercontent.com/6623948/216015585-3fe9e5c5-b0ae-438f-8881-05c371a44164.png)

**Comment by ankh2054** [comment]
I have the same problem.
<img width="414" alt="image" src="https://user-images.githubusercontent.com/6784287/219850792-5c59c67e-14cd-4d23-89b9-792217f37c24.png">

**Comment by Natgho** [comment]
The problem is fixed in new version. I contacted with Termius. Update termius and re-try.
